---
become: yes
become_user: root
tasks:
  - name: Update the System
    ansible.builtin.command: 
      argv:
        - apt update && apt upgrade -y
        - apt install vim -y
        - apt install net-tools -y
        - apt install unzip -y
        - apt install curl -y

  - name: Install Docker and Give Access to Non-Root User
    ansible.builtin.command: 
      argv: 
        - curl -fsSL https://get.docker.com -o get-docker.sh
        - sh get-docker.sh
        - docker --version
        - usermod -aG docker {{ user_name }}

  - name: Install AWS CLI
    ansible.builtin.command: 
      argv: 
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        - unzip awscliv2.zip
        - ./aws/install
        - aws --version

  - name: Install Git 
    ansible.builtin.command: 
      argv: 
        - apt install git

  - name: Install Python3 
    ansible.builtin.command: 
      argv: 
        - apt update
        - apt install build-essential software-properties-common -y
        - add-apt-repository -y ppa:deadsnakes/ppa
        - apt update
        - apt install {{ python3_version }} -y
        - /usr/bin/{{ python3_version }} --version

  - name: Install VSCode 
    ansible.builtin.command: 
      argv: 
        - apt update && apt upgrade -y
        - apt install software-properties-common apt-transport-https wget
        - wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
        - add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
        - apt update && sudo apt upgrade -y
        - code --version

  - name: Install Postman 
    ansible.builtin.command: 
      argv: 
        - apt update
        - snap install postman

  - name: Install Postman 
    ansible.builtin.command: 
      argv: 
        - apt update
        - snap install postman

  - name: Install JAVA JDK 
    ansible.builtin.command: 
      argv: 
        - apt update
        - apt install default-jre
        - java -version

  - name: Install JAVA JDK 
    ansible.builtin.command: 
      argv: 
        - apt update
        - apt install default-jre
        - java -version

  - name: Install NodeJS and NPM
    ansible.builtin.command: 
      argv: 
        - apt update && apt upgrade -y
        - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
        - nvm --version
        - source ~/.bashrc
        - nvm install {{ node_version }}
        - node -v
        - npm -v
