---
    - name: Update the System
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install required packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - vim
        - net-tools
        - unzip
        - curl
        update_cache: yes


    - name: Install latest version of "JAVA"
      apt:
        name: default-jre
        update_cache: yes

    - name: Download Docker installation script
      get_url:
        url: "https://get.docker.com"
        dest: "/tmp/get-docker.sh"

    - name: Run Docker installation script
      command: "sh /tmp/get-docker.sh"

    - name: Verify Docker installation
      command: docker --version

    - name: Add user to docker group
      user:
        name: rocky
        groups: docker
        append: yes

    - name: Download AWS CLI installer
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: "/tmp/awscliv2.zip"

    - name: Unzip AWS CLI installer
      unarchive:
        src: "/tmp/awscliv2.zip"
        dest: "/tmp/"

    - name: Run AWS CLI installer
      command: "/tmp/aws/install"

    - name: Check AWS CLI version
      command: "aws --version"

    - name: Install Prerquisites of Code
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - software-properties-common
        - apt-transport-https
        - wget

    - name: Add VSCode repository GPG key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add VSCode repository
      apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
        state: present

    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install VSCode
      apt:
        name: code
        state: present

    - name: Update the system Postman
      apt:
        update_cache: yes

    - name: Install Postman
      command: "snap install postman"
