---
    - name: Update the System
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install required packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - vim
        - net-tools
        - unzip
        - curl
        update_cache: yes

    - name: Install latest version of "JAVA"
      apt:
        name: default-jre
        update_cache: yes

    - name: Download Docker installation script
      get_url:
        url: "https://get.docker.com"
        dest: "/tmp/get-docker.sh"

    - name: Run Docker installation script
      command: "sh /tmp/get-docker.sh"

    - name: Verify Docker installation
      command: docker --version

    - name: Add user to docker group
      user:
        name: rocky
        groups: docker
        append: yes

    - name: Download AWS CLI installer
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: "/tmp/awscliv2.zip"

    - name: Unzip AWS CLI installer
      unarchive:
        src: "/tmp/awscliv2.zip"
        dest: "/tmp/"

    - name: Run AWS CLI installer
      command: "/tmp/aws/install"

    - name: Check AWS CLI version
      command: "aws --version"

    - name: Install VSCode
      command: "snap install --classic code"

    - name: Update the system for Postman
      apt:
        update_cache: yes

    - name: Install Postman
      command: "snap install postman"
